# Generated by Django 2.1.7 on 2019-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20180501_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(),
        ),
    ]
