# Generated by Django 2.1.7 on 2019-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contestannouncement',
            name='content',
            field=models.TextField(),
        ),
    ]
