# Generated by Django 2.1.7 on 2019-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.TextField(),
        ),
    ]
